"""updated company models

Revision ID: 053680f4734e
Revises: 33e0a897e9ce
Create Date: 2021-07-31 16:16:28.744566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053680f4734e'
down_revision = '33e0a897e9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('item_price_in_cents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_price_in_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_packages', schema=None) as batch_op:
        batch_op.drop_column('package_price_in_cents')

    op.drop_table('company_products')
    # ### end Alembic commands ###
