"""added columns to Package model to take into account transfer functionality

Revision ID: 09ceb9e9cdd4
Revises: f1a812539b99
Create Date: 2021-07-05 22:48:56.170222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ceb9e9cdd4'
down_revision = 'f1a812539b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_num_times_transferred', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_transferred', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('transferred_from_phone_number', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('transferred_from_phone_number')
        batch_op.drop_column('is_transferred')
        batch_op.drop_column('package_num_times_transferred')

    # ### end Alembic commands ###
