"""empty message

Revision ID: 100dfa3f40d6
Revises: 00773c3f3da1
Create Date: 2021-08-12 23:54:38.912392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100dfa3f40d6'
down_revision = '00773c3f3da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
