"""empty message

Revision ID: 2c41b70d7830
Revises: 8bcd68d1d41c
Create Date: 2021-08-17 23:19:20.081051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c41b70d7830'
down_revision = '8bcd68d1d41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outlet_name', sa.String(length=64), nullable=True))

    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outlet_name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('outlet_name')

    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.drop_column('outlet_name')

    # ### end Alembic commands ###
