"""added email and password fields in customer model

Revision ID: 47f0c3870581
Revises: b976417fbd6d
Create Date: 2021-06-29 15:13:43.741516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f0c3870581'
down_revision = 'b976417fbd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('customer', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_column('customer', 'password_hash')
    op.drop_column('customer', 'email')
    # ### end Alembic commands ###
