"""changed Package column names

Revision ID: 5eafbc1e5d6f
Revises: 09ceb9e9cdd4
Create Date: 2021-07-05 23:01:52.186213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eafbc1e5d6f'
down_revision = '09ceb9e9cdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_num_total_uses_at_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('package_num_used_when_keyed', sa.Integer(), nullable=True))
        batch_op.drop_column('package_total_uses_at_start')
        batch_op.drop_column('package_uses_left_when_keyed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_uses_left_when_keyed', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('package_total_uses_at_start', sa.INTEGER(), nullable=True))
        batch_op.drop_column('package_num_used_when_keyed')
        batch_op.drop_column('package_num_total_uses_at_start')

    # ### end Alembic commands ###
