"""initial migration

Revision ID: 72bcaf1b5e86
Revises: 
Create Date: 2021-07-06 23:56:32.683581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bcaf1b5e86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_email'), ['email'], unique=True)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=True)

    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.Column('package_name', sa.String(length=128), nullable=True),
    sa.Column('package_num_total_uses_at_start', sa.Integer(), nullable=True),
    sa.Column('package_num_used_when_keyed', sa.Integer(), nullable=True),
    sa.Column('package_num_times_used_after_keyed', sa.Integer(), nullable=True),
    sa.Column('package_num_times_transferred', sa.Integer(), nullable=True),
    sa.Column('package_price_paid_in_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_ported_over', sa.Boolean(), nullable=True),
    sa.Column('is_transferred', sa.Boolean(), nullable=True),
    sa.Column('transferred_from_phone_number', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['cust_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_created_at'), ['created_at'], unique=False)

    op.create_table('package_use',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_use', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_use_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_use', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_use_created_at'))

    op.drop_table('package_use')
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_created_at'))

    op.drop_table('package')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))

    op.drop_table('customer')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_email'))

    op.drop_table('admin')
    op.drop_table('user')
    # ### end Alembic commands ###
