"""created package and packageuse

Revision ID: b16e2e2ffc48
Revises: 47f0c3870581
Create Date: 2021-06-30 14:49:13.693655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16e2e2ffc48'
down_revision = '47f0c3870581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.Column('package_name', sa.String(length=64), nullable=True),
    sa.Column('package_total_uses_at_start', sa.Integer(), nullable=True),
    sa.Column('package_uses_left_when_keyed', sa.Integer(), nullable=True),
    sa.Column('package_num_times_used_after_keyed', sa.Integer(), nullable=True),
    sa.Column('package_price_paid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cust_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_created_at'), 'package', ['created_at'], unique=False)
    op.create_table('package_use',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_use_created_at'), 'package_use', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_use_created_at'), table_name='package_use')
    op.drop_table('package_use')
    op.drop_index(op.f('ix_package_created_at'), table_name='package')
    op.drop_table('package')
    # ### end Alembic commands ###
