"""added bool field to package model

Revision ID: bdef9e9d4331
Revises: b16e2e2ffc48
Create Date: 2021-06-30 14:55:46.064792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdef9e9d4331'
down_revision = 'b16e2e2ffc48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'is_active')
    # ### end Alembic commands ###
